labels <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
columnlines <- c("black","red","blue")
par(mfrow=c(2,2))
plot(subpowerData$powerTime, subpowerData$Global_active_power, type="l", col="green", xlab="", ylab="Global Active Power")
plot(subpowerData$powerTime, subpowerData$Voltage, type="l", col="orange", xlab="datetime", ylab="Voltage")
plot(subpowerData$powerTime, subpowerData$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(subpowerData$powerTime, subpowerData$Sub_metering_2, type="l", col="red")
lines(subpowerData$powerTime, subpowerData$Sub_metering_3, type="l", col="blue")
legend("topright", bty="n", legend=labels, lty=1, col=columnlines)
plot(subpowerData$powerTime, subpowerData$Global_reactive_power, type="l", col="blue", xlab="datetime", ylab="Global_reactive_power")