unzip("C:\\Users\\380235\\Documents\\DATA_SC\\household_power_consumption.zip", overwrite = T, exdir = "C:\\Users\\380235\\Documents\\DATA_SC\\power_consumption")
powerData <- read.table(("C:\\Users\\380235\\Documents\\DATA_SC\\power_consumption\\household_power_consumption.txt"), header=T, sep=";", na.strings="?")
subpowerData <- powerData[powerData$Date %in% c("1/2/2007","2/2/2007"),]
powerTime <-strptime(paste(subpowerData$Date, subpowerData$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
subpowerData <- cbind(powerTime, subpowerData)
hist(subpowerData$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
plot(subpowerData$powerTime, subpowerData$Global_active_power, type="l", col="black", xlab="", ylab="Global Active Power (kilowatts)")
columnlines <- c("black", "red", "blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
plot(subpowerData$powerTime, subpowerData$Sub_metering_1, type="l", col=columnlines[1], xlab="", ylab="Energy sub metering")
lines(subpowerData$powerTime, subpowerData$Sub_metering_2, col=columnlines[2])
lines(subpowerData$powerTime, subpowerData$Sub_metering_3, col=columnlines[3])
legend("topright", legend=labels, col=columnlines, lty="solid")
labels <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
columnlines <- c("black","red","blue")
par(mfrow=c(2,2))
plot(subpowerData$powerTime, subpowerData$Global_active_power, type="l", col="green", xlab="", ylab="Global Active Power")
plot(subpowerData$powerTime, subpowerData$Voltage, type="l", col="orange", xlab="datetime", ylab="Voltage")
plot(subpowerData$powerTime, subpowerData$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(subpowerData$powerTime, subpowerData$Sub_metering_2, type="l", col="red")
lines(subpowerData$powerTime, subpowerData$Sub_metering_3, type="l", col="blue")
legend("topright", bty="n", legend=labels, lty=1, col=columnlines)
plot(subpowerData$powerTime, subpowerData$Global_reactive_power, type="l", col="blue", xlab="datetime", ylab="Global_reactive_power")